### PR TITLE
Improve autocompletion for dollar commands

### PR DESCRIPTION
**Pull request by christophe-gouel**
When implementing the autocompletion, I had forgotten that gams dollar commands exist in 3 formats:

- Normal format when starting with 1 $ on first column
- When indented they start with 2 $
- Following another dollar command without $

The autocompletion was not adapted to all format.

Now it is.

### CODE REVIEW

**Comment by christophe-gouel** [comment]
I have also moved all model types (cns, nlp, ...) to lowercase. They were uppercase in the file provided by GAMS, but in all GAMS documentation, the standard is to use lowercase for them.

**Comment by christophe-gouel** [comment]
After these minor changes, for me this fixes #6.

**Comment by christophe-gouel** [comment]
Hi @ShiroTakeda,

I have made very minor updates, as well as the updates mentionned above:
- Updated the commands to GAMS 47.2
- Add all possible combinations of dollar conditional expression (like `$if not exist`) for proper syntax highlighting

Things work very well on my side with syntax highlighting being much more complete for dollar commands.

This PR should take you no time to review.

**Comment by ShiroTakeda** [comment]
Thank you for your pull request.

I would like to incorporate your changes, but could you please send the pull request to the "develop" branch instead of the "master" branch?

I would like to first integrate new features into the "develop" branch, check their functionality, and then reflect them in the "master" branch.

**Comment by christophe-gouel** [comment]
It should be good now. Let me know if you need any help. I have left for vacation for a week without a laptop, so anything requiring coding will have to wait for a week.

**Pull request merged**
